// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtJop9VCd_Yl5gyb_WlBC2T2RY610DFl8',
    appId: '1:897624858919:web:a17f55e793ae5be5060902',
    messagingSenderId: '897624858919',
    projectId: 'logical-pilot-345102',
    authDomain: 'logical-pilot-345102.firebaseapp.com',
    storageBucket: 'logical-pilot-345102.appspot.com',
    measurementId: 'G-1TJPFCX3HT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR5M4BycfJ4iasfywOzvYb_LCD_bf3yA8',
    appId: '1:897624858919:android:34b61c8d16e33d85060902',
    messagingSenderId: '897624858919',
    projectId: 'logical-pilot-345102',
    storageBucket: 'logical-pilot-345102.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0snnPqC-GNu8gVCI1k4KxSc23J5Do1aI',
    appId: '1:897624858919:ios:6e92aab5746b9b40060902',
    messagingSenderId: '897624858919',
    projectId: 'logical-pilot-345102',
    storageBucket: 'logical-pilot-345102.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0snnPqC-GNu8gVCI1k4KxSc23J5Do1aI',
    appId: '1:897624858919:ios:d4ad7318e85768b4060902',
    messagingSenderId: '897624858919',
    projectId: 'logical-pilot-345102',
    storageBucket: 'logical-pilot-345102.appspot.com',
    iosBundleId: 'com.example.spotify.RunnerTests',
  );
}
